name: surveyapp
description: An app which allows users to fill out a survey on a business they recently visited
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_spinkit: ^4.1.2+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  collection: ^1.14.11
  barcode_scan: any
  flutter_launcher_icons: "^0.7.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/icon.png"
  image_path_android: "lib/assets/icon.png"

flutter:
  uses-material-design: true
